apiVersion: v1
kind: Service
metadata:
  name: flask-rest
spec:
  type: NodePort
  selector:
    app: flask-rest
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30555
