apiVersion: v1
kind: Service
metadata:
  name: image-server
spec:
  type: NodePort
  selector:
    app: image-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30556

