apiVersion: v1
kind: Service
metadata:
  name: jinja-ui
spec:
  type: NodePort
  selector:
    app: jinja-ui
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
      nodePort: 30554
